import { describe, expect, test } from "bun:test";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");

describe("npm release-age enforcement", () => {
  const bunfig = readFileSync(join(ROOT, "bunfig.toml"), "utf8");
  const setupAztec = readFileSync(join(ROOT, ".github/actions/setup-aztec/action.yml"), "utf8");

  test("keeps the global seven-day gate without package exemptions", () => {
    expect(bunfig).toContain("minimumReleaseAge = 604800");
    expect(bunfig).not.toContain("minimumReleaseAgeExcludes");
  });

  test("keeps the npm bootstrap restricted without bypassing release age", () => {
    expect(setupAztec).toContain("export npm_config_min_release_age=7");
    expect(setupAztec).not.toContain("npm_config_min_release_age_exclude");
    expect(setupAztec).toContain("allow-scripts[]=");
  });

  test("gates frozen CI installs and checks the lock generated by forced Aztec updates", () => {
    const files = [
      join(ROOT, ".github/actions/setup-aztec/action.yml"),
      join(ROOT, ".github/actions/setup-presto/action.yml"),
      ...readdirSync(join(ROOT, ".github/workflows"), { withFileTypes: true })
        .filter((entry) => entry.isFile() && entry.name.endsWith(".yml"))
        .map((entry) => join(ROOT, ".github/workflows", entry.name)),
    ];

    for (const file of files) {
      const workflow = readFileSync(file, "utf8");
      for (const match of workflow.matchAll(/run: bun install --frozen-lockfile/g)) {
        expect(workflow.slice(Math.max(0, match.index - 160), match.index)).toContain(
          "uses: ./.github/actions/check-dependency-age",
        );
      }
    }

    const aztecUpdate = readFileSync(join(ROOT, ".github/workflows/_aztec-update.yml"), "utf8");
    expect(aztecUpdate).toMatch(
      /run: bun install[\s\S]{0,320}GITHUB_TOKEN: \$\{\{ github\.token \}\}[\s\S]{0,80}run: bun scripts\/dependency-age\.ts --base HEAD/,
    );
  });
});
